# -*- mode: ruby; encoding: utf-8 -*-
# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command

lib = File.expand_path('../lib/', __FILE__)
$:.unshift lib unless $:.include?(lib)

require 'capistrano-offroad/version'

Gem::Specification.new do |s|
  s.name = "capistrano-offroad"
  s.version = CapistranoOffroad::VERSION::STRING
  s.summary = "Capistrano add-ons and recipes for non-rails projects"
  s.description = "Capistrano add-ons and recipes for non-rails projects" # FIXME
  s.authors = ["Maciej Pasternacki"]
  s.email = "maciej@pasternacki.net"
  s.homepage = "http://github.com/mpasternacki/capistrano-offroad"

  s.required_rubygems_version = ">= 1.3.6"
  s.files = Dir.glob("lib/**/*.rb") + %w(README LICENSE)
  s.require_paths = ["lib"]
end
